version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cloud-urlwatch"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1mjhgvy31ucmj"
s3_prefix = "cloud-urlwatch"
region = "eu-west-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "PushoverToken=\"{{resolve:ssm:pushoverToken:1}}\" PushoverUser=\"{{resolve:ssm:pushoverUser:1}}\" EmailHost=\"{{resolve:secretsmanager:cloud-urlwatch/email-details:SecretString:EmailHost}}\" EmailPort=\"{{resolve:secretsmanager:cloud-urlwatch/email-details:SecretString:EmailPort}}\" EmailUser=\"{{resolve:secretsmanager:cloud-urlwatch/email-details:SecretString:EmailUser}}\" EmailPass=\"{{resolve:secretsmanager:cloud-urlwatch/email-details:SecretString:EmailPass}}\" EmailFrom=\"{{resolve:secretsmanager:cloud-urlwatch/email-details:SecretString:EmailFrom}}\" EmailRcpt=\"{{resolve:secretsmanager:cloud-urlwatch/email-details:SecretString:EmailRcpt}}\""
image_repositories = []
