AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-urlwatch

  Scheduled running of URLWatch within an ECS task


Parameters:

  # Secret keys
  PushoverToken:
    Type: String
    Description: Token used to notify built packages via Pushover
    Default: '{{resolve:ssm:pushoverToken:1}}'
  PushoverUser:
    Type: String
    Description: User used to notify built packages via Pushover
    Default: '{{resolve:ssm:pushoverUser:1}}'

  # Email Details
  EmailHost:
    Type: String
    Description: IMAP server details to email results to
    Default: '{{resolve:secretsmanager:cloud-urlwatch/email-details:EmailHost}}'
  EmailPort:
    Type: String
    Description: Port of the IMAP
    Default: '{{resolve:secretsmanager:cloud-urlwatch/email-details:EmailPort}}'
  EmailUser:
    Type: String
    Description: Username of the IMAP server
    Default: '{{resolve:secretsmanager:cloud-urlwatch/email-details:EmailUser}}'
  EmailPass:
    Type: String
    Description: Password of the IMAP server
    Default: '{{resolve:secretsmanager:cloud-urlwatch/email-details:EmailPass}}'
  EmailFrom:
    Type: String
    Description: Address to send the email from
    Default: '{{resolve:secretsmanager:cloud-urlwatch/email-details:EmailFrom}}'
  EmailRcpt:
    Type: String
    Description: Address to send the email to
    Default: '{{resolve:secretsmanager:cloud-urlwatch/email-details:EmailRcpt}}'


Globals:
  Function:
    Timeout: 3
    Runtime: python3.9

Resources:

  ###
  # Functions
  ##

  UrlwatchFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-urlwatch-scheduler"
      Description: Scheduled execution of the Urlwatch ECS task
      CodeUri: urlwatch_lambda
      Handler: urlwatch_start_ecs.handler
      Timeout: 60
      Role: !GetAtt ExtractRole.Arn
      DeadLetterQueue:
        TargetArn: !GetAtt ErrorQueue.Arn
        Type: SQS
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt ErrorQueue.QueueName
      Environment:
        Variables:
          ECS_CLUSTER: !Ref UrlwatchCluster
          TASK_DEFN: !Ref UrlwatchTaskDefinition
      Events:
        RepoUpdateSchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 0 * * ? *)
      Layers:
        - !Ref AwsLayer

  ErrorHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-urlwatch-error-handler"
      Description: Catch and notify on errors in other functions
      CodeUri: reporting
      Handler: error_reporting.handler
      Timeout: 30
      Environment:
        Variables:
          PUSHOVER_TOKEN: !Ref PushoverToken
          PUSHOVER_USER: !Ref PushoverUser
      Events:
        ErrorQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt ErrorQueue.Arn

  ###
  # Layers
  ##

  AwsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "${AWS::StackName}-dependencies"
      Description: Dependencies for PKGBUILD apps
      ContentUri: src/
      CompatibleRuntimes:
        - python3.8
        - python3.9
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain

  ###
  # Queues
  ##

  ErrorQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-error-queue"
      VisibilityTimeout: 30

  ###
  # VPC
  ##

  UrlwatchVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.31.0.0/16
      EnableDnsHostnames: True
      EnableDnsSupport: True

  UrlwatchSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 172.31.1.0/24
      VpcId: !Ref MountTargetVPC
      AvailabilityZone: "eu-west-1a"

  ###
  # EFS
  ##

  UrlwatchFileSystem:
    Type: 'AWS::EFS::FileSystem'
    Properties:
      PerformanceMode: generalPurpose
      Encrypted: true
      FileSystemPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "elasticfilesystem:ClientMount"
            Principal:
              AWS: "*"

  UrlwatchMountPoint:
    Type: 'AWS::EFS::MountTarget'
    Properties:
      FileSystemId: !Ref UrlwatchFileSystem
      SubnetId: !Ref UrlwatchSubnet
      SecurityGroups:
      - !GetAtt UrlwatchVPC.DefaultSecurityGroup

  UrlwatchAccessPoint:
    Type: 'AWS::EFS::AccessPoint'
    Properties:
      FileSystemId: !Ref UrlwatchFileSystem
      PosixUser:
        Uid: "1000"
        Gid: "1000"
      RootDirectory:
        CreationInfo:
          OwnerGid: "1000"
          OwnerUid: "1000"
          Permissions: "0777"
        Path: "/efs"

  ###
  # ECS
  ##

  UrlwatchCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${AWS::StackName}-cluster"

  UrlwatchTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn:
      - UrlwatchFileSystem
    Properties:
      Family: !Sub "${AWS::StackName}-task"
      Cpu: "256"
      Memory: "512"
      NetworkMode: "awsvpc"
      RequiresCompatibilities:
        - "FARGATE"
      TaskRoleArn: !GetAtt UrlwatchTaskRole.Arn
      ExecutionRoleArn: !GetAtt UrlwatchTaskRole.Arn
      ContainerDefinitions:
        - Name: "${AWS::StackName}-docker-urlwatch"
          Image: "couldinho/docker-urlwatch"
          LogConfiguration:
            LogDriver: "awslogs"
            Options:
              awslogs-group: "/ecs/docker-urlwatch"
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: "ecs"
          Environment:
            - Name: "UW_HOST"
              Value: !Ref EmailHost
            - Name: "UW_PORT"
              Value: !Ref EmailPort
            - Name: "UW_USER"
              Value: !Ref EmailUser
            - Name: "UW_PASS"
              Value: !Ref EmailPass
            - Name: "UW_FROM"
              Value: !Ref EmailFrom
            - Name: "UW_RCPT"
              Value: !Ref EmailRcpt
          MountPoints:
            - SourceVolume: data
              ContainerPath: /root/.urlwatch
      Volumes:
      - Name: data
        EFSVolumeConfiguration:
          FilesystemId: !Ref UrlwatchFileSystem
          TransitEncryption: DISABLED


  ###
  # Roles
  ##

  UrlwatchTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-task-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub "${AWS::StackName}-task-policy"

