name: Docker Build and Push

on:
  schedule:
    - cron: '0 0 * * 2'
  push:
    branches: [ master ]

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:

      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASS }}

      -
        name: Build and push
        uses: docker/build-push-action@v2
        working-directory: ./docker-urlwatch
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.DOCKER_USER }}/aur-pkg-update:latest
